### ISSUE TITLE
Support air-gapped installations

### ISSUE THREAD

**Issue by mjtrangoni** [andrewrothstein/ansible-k9s#4]
Hi @andrewrothstein,

I am missing a feature for installing k9s on isolated environments, which are not able to download k9s from GitHub.
Are you interested on supporting this case?

**Comment by andrewrothstein** [comment]
I intentionally build the download URL from the [k9s_mirror](https://github.com/andrewrothstein/ansible-k9s/blob/628f46836445672a7b204a494447c1064f7b03ca/defaults/main.yml#L13) var. if the target host can not access github.com, feel free to create a local mirror on the host's side of the air gap holding the released artifacts.

**Comment by andrewrothstein** [comment]
I intentionally build the download URL from the [k9s_mirror](https://github.com/andrewrothstein/ansible-k9s/blob/628f46836445672a7b204a494447c1064f7b03ca/defaults/main.yml#L13) var. if the target host can not access github.com, feel free to create a local mirror on the host's side of the air gap holding the released artifacts.

**Comment by andrewrothstein** [comment]
I intentionally build the download URL from the [k9s_mirror](https://github.com/andrewrothstein/ansible-k9s/blob/628f46836445672a7b204a494447c1064f7b03ca/defaults/main.yml#L13) var. if the target host can not access github.com, feel free to create a local mirror on the host's side of the air gap holding the released artifacts.
